### ISSUE TITLE
AppVeyorClient should be public

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AppVeyor#16]
I propose that `AppVeyorClient` should be public in order to be used in other projects. Alternatively, it could be move a separate project (and separate nuget package) which could then be referenced by other projects.

**Comment by gep13** [comment]
@Jericho I don't think I have any objections to this. Was this something that you would be interested in submitting a PR for?

**Comment by Jericho** [comment]
Sure. Although it's been so long since I raised this issue, I honestly don't remember why I needed to reference this class.

**Comment by Jericho** [comment]
Out of the 21 classes in this project, 15 were already marked as public. The access modifier on the other 6 classes was omitted which seems like a simple oversight. 

I'm submitting a PR to explicitly mark the remaining 6 classes as public.
